apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: grpc-web-server
  name: grpc-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grpc-web-server
  strategy: {}
  template:
    metadata:
      labels:
        run: grpc-web-server
    spec:
      containers:
      - image: asia.gcr.io/agdc-k8s/grpc-web-server
        name: grpc-web-server
        envFrom:
        - configMapRef:
            name: grpc-web-server-config
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: 100m
status: {}
